src/java/es/condenast/jpa/entities/CnmasRangoEdad.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.condenast.jpa.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author ivan.fernandez
 */
@Entity
@Table(name = "cnmas_rango_edad")
@NamedQueries({
    @NamedQuery(name = "CnmasRangoEdad.findAll", query = "SELECT c FROM CnmasRangoEdad c"),
    @NamedQuery(name = "CnmasRangoEdad.findAllOrderByDesde", query = "SELECT c FROM CnmasRangoEdad c ORDER BY c.desde"),
    @NamedQuery(name = "CnmasRangoEdad.findByIdNivelIngreso", query = "SELECT c FROM CnmasRangoEdad c WHERE c.idRango = :idRango"),
    @NamedQuery(name = "CnmasRangoEdad.findByNombre", query = "SELECT c FROM CnmasRangoEdad c WHERE c.nombre = :nombre"),
    @NamedQuery(name = "CnmasRangoEdad.findByDesde", query = "SELECT c FROM CnmasRangoEdad c WHERE c.desde = :desde"),
    @NamedQuery(name = "CnmasRangoEdad.findByHasta", query = "SELECT c FROM CnmasRangoEdad c WHERE c.hasta = :hasta")})
public class CnmasRangoEdad implements Serializable{
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "IdRango")
    private Short idRango;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 200)
    @Column(name = "Nombre")
    private String nombre;
    @Column(name = "Desde")
    private Short desde;
    @Column(name = "Hasta")
    private Short hasta;

    /**
     * @return the idRango
     */
    public Short getIdRango() {
        return idRango;
    }

    /**
     * @param idRango the idRango to set
     */
    public void setIdRango(Short idRango) {
        this.idRango = idRango;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the desde
     */
    public Short getDesde() {
        return desde;
    }

    /**
     * @param desde the desde to set
     */
    public void setDesde(Short desde) {
        this.desde = desde;
    }

    /**
     * @return the hasta
     */
    public Short getHasta() {
        return hasta;
    }

    /**
     * @param hasta the hasta to set
     */
    public void setHasta(Short hasta) {
        this.hasta = hasta;
    }
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idRango != null ? idRango.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof CnmasRangoEdad)) {
            return false;
        }
        CnmasRangoEdad other = (CnmasRangoEdad) object;
        if ((this.idRango == null && other.idRango != null) || (this.idRango != null && !this.idRango.equals(other.idRango))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "es.condenast.jpa.entities.CnmasRangoEdad[ idRango=" + idRango + " ]";
    }
}

src/java/es/condenast/jsf/VietlLogAdminController.java
package es.condenast.jsf;

import es.condenast.ingesta.entities.Log;
import es.condenast.ingesta.entities.LogRegla;
import es.condenast.ingesta.entities.LogTransformacion;
import es.condenast.ingesta.entities.LogValidacion;
import es.condenast.ingesta.entities.LogValidacionDetalle;
import es.condenast.ingesta.entities.LogWarning;
import es.condenast.ingesta.helper.CSVUtils;
import es.condenast.ingesta.helper.TimeUtils;
import es.condenast.jpa.entities.CnetlEstado;
import es.condenast.jpa.entities.CnetlFuente;
import es.condenast.jpa.entities.CnetlFuenteTipo;
import es.condenast.jpa.entities.CnetlPoolLog;
import es.condenast.jpa.entities.CnetlPoolLogWarning;
import es.condenast.jpa.entities.VietlLog;
import es.condenast.jpa.entities.VietlLogRegla;
import es.condenast.jpa.entities.VietlLogTransformacion;
import es.condenast.jpa.entities.VietlLogValidacion;
import es.condenast.jpa.entities.VietlLogValidacionLinea;
import es.condenast.jpa.session.CnetlEstadoFacade;
import es.condenast.jpa.session.CnetlFuenteFacade;
import es.condenast.jpa.session.CnetlFuenteTipoFacade;
import es.condenast.jpa.session.CnetlPoolLogFacade;
import es.condenast.jpa.session.CnetlPoolLogWarningFacade;
import es.condenast.jsf.util.JsfUtil;
import es.condenast.jsf.util.PaginationHelper;
import es.condenast.jpa.session.VietlLogFacade;
import es.condenast.jpa.session.VietlLogReglaFacade;
import es.condenast.jpa.session.VietlLogTransformacionFacade;
import es.condenast.jpa.session.VietlLogValidacionFacade;
import es.condenast.jpa.session.VietlLogValidacionLineaFacade;
import java.io.IOException;
import java.io.OutputStream;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpServletResponse;

@Named("vietlLogAdminController")
@SessionScoped
public class VietlLogAdminController implements Serializable {
    private static final String CSV_SEPARADOR = ";";
    private VietlLog current;
    private DataModel items = null;
    @EJB
    private VietlLogFacade ejbFacade;
    @EJB
    private CnetlFuenteFacade ejbCnetlFuente;
    @EJB
    private CnetlFuenteTipoFacade ejbCnetlFuenteTipo;
    @EJB
    private CnetlEstadoFacade ejbCnetlEstado;
    @EJB
    private CnetlPoolLogFacade ejbCnetlPoolLogFacade;
    @EJB
    private VietlLogReglaFacade ejbLogReglaFacade;
    @EJB
    private VietlLogTransformacionFacade ejbLogTransformacionFacade;
    @EJB
    private VietlLogValidacionFacade ejbLogValidacionFacade;
    @EJB
    private VietlLogValidacionLineaFacade ejbLogValidacionLineaFacade;
    @EJB
    private CnetlPoolLogWarningFacade ejbLogWarningFacade;
    
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private Date fechaDesde;
    private Date fechaHasta;
    private CnetlFuente fuente;
    private CnetlFuenteTipo fuenteTipo;
    private CnetlEstado estado;
    
    public VietlLogAdminController() {
    }

    public VietlLog getSelected() {
        if (current == null) {
            current = new VietlLog();
            selectedItemIndex = -1;
        }
        return current;
    }

    private VietlLogFacade getFacade() {
        return ejbFacade;
    }

    /**
     * @return the ejbCnetlFuente
     */
    public CnetlFuenteFacade getEjbCnetlFuente() {
        return ejbCnetlFuente;
    }

    /**
     * @return the ejbCnetlFuenteTipo
     */
    public CnetlFuenteTipoFacade getEjbCnetlFuenteTipo() {
        return ejbCnetlFuenteTipo;
    }

    /**
     * @return the ejbCnetlEstado
     */
    public CnetlEstadoFacade getEjbCnetlEstado() {
        return ejbCnetlEstado;
    }

    /**
     * @return the ejbCnetlPoolLogFacade
     */
    public CnetlPoolLogFacade getEjbCnetlPoolLogFacade() {
        return ejbCnetlPoolLogFacade;
    }

    public VietlLogReglaFacade getEjbLogReglaFacade() {
        return ejbLogReglaFacade;
    }

    public VietlLogTransformacionFacade getEjbLogTransformacionFacade() {
        return ejbLogTransformacionFacade;
    }

    public VietlLogValidacionFacade getEjbLogValidacionFacade() {
        return ejbLogValidacionFacade;
    }

    public VietlLogValidacionLineaFacade getEjbLogValidacionLineaFacade() {
        return ejbLogValidacionLineaFacade;
    }

    public CnetlPoolLogWarningFacade getEjbLogWarningFacade() {
        return ejbLogWarningFacade;
    }

    /**
     * @return the fechaDesde
     */
    public Date getFechaDesde() {
        return fechaDesde;
    }

    /**
     * @param fechaDesde the fechaDesde to set
     */
    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }

    /**
     * @return the fechaHasta
     */
    public Date getFechaHasta() {
        return fechaHasta;
    }

    /**
     * @param fechaHasta the fechaHasta to set
     */
    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }

    /**
     * @return the fuente
     */
    public CnetlFuente getFuente() {
        return fuente;
    }

    /**
     * @param fuente the fuente to set
     */
    public void setFuente(CnetlFuente fuente) {
        this.fuente = fuente;
    }

    /**
     * @return the fuenteTipo
     */
    public CnetlFuenteTipo getFuenteTipo() {
        return fuenteTipo;
    }

    /**
     * @param fuenteTipo the fuenteTipo to set
     */
    public void setFuenteTipo(CnetlFuenteTipo fuenteTipo) {
        this.fuenteTipo = fuenteTipo;
    }

    /**
     * @return the estado
     */
    public CnetlEstado getEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(CnetlEstado estado) {
        this.estado = estado;
    }


    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(25) {

                @Override
                public int getItemsCount() {
                    return ejbFacade.countAdminLog(fechaDesde, fechaHasta, fuenteTipo.getNombre(), fuente == null?null:fuente.getNombre(), estado == null?null:estado.getNombre());
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(ejbFacade.findAdminLog(fechaDesde, fechaHasta, getFuenteTipo().getNombre(), fuente == null?null:fuente.getNombre(), 
                            estado == null?null:estado.getNombre(), new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String destroyAllItems() {
        try {
            Iterator log = items.iterator();
            while (log.hasNext()){
                VietlLog vietlLog = (VietlLog) log.next();
                CnetlPoolLog pooLog = ejbCnetlPoolLogFacade.findByIdPool(vietlLog.getIdPool()).get(0);
                ejbCnetlPoolLogFacade.remove(pooLog);
            }
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("PersistenceErrorOccured"));
        }
        return buscarLogs();
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public String toPage(Integer page) {
        getPagination().toPage(page);
        recreateModel();
        return "List";
    }
    
    public String buscarLogs(){
        recreateModel();
        if (fechaDesde == null && fechaHasta == null && fuenteTipo == null){
            String msg = ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("AdminLogValidate");          
            JsfUtil.addErrorMessage(msg);
            return "";
        }
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public VietlLog getVietlLog(long id) {
        return ejbFacade.find(id);
    }

    public String exportToCSV() {
        downloadFile();  
        return "";
    }
    
    public String showDetailList() {
        current = (VietlLog) getItems().getRowData();
        downloadPoolFile(current);
        return "";
    }
    
    public String destroyItem() {
        current = (VietlLog) getItems().getRowData();
        try {
            CnetlPoolLog pooLog = ejbCnetlPoolLogFacade.findByIdPool(current.getIdPool()).get(0);
            ejbCnetlPoolLogFacade.remove(pooLog);
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("PersistenceErrorOccured"));
        }
        return buscarLogs();
    }
    
    @FacesConverter(forClass = VietlLog.class)
    public static class VietlLogAdminControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {

web/cnmasRangoEdad/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">#{messages.BreadCrumbCrearRangoEdad}</ui:define>
        <ui:define name="body">
            <h:form>
                <p:breadCrumb>
                    <p:menuitem value="#{messages.BreadCrumbInicio}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbMaestros}" styleClass="itemBreadCrumb" />
                    <p:menuitem value="#{messages.BreadCrumbRangoEdad}" styleClass="itemBreadCrumb" url="./List.xhtml" />
                    <p:menuitem value="#{messages.BreadCrumbCrearRangoEdad}" styleClass="itemBreadCrumb"/>
                </p:breadCrumb>
            </h:form>
            <br />
            <br />

            <p:dialog header="#{messages.BreadCrumbCrearRangoEdad}" visible="#{not empty facesContext.messageList}" styleClass="dialog">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </p:dialog>

            <h:form id="formId">
                <div class="formulario">
                    <p:panelGrid styleClass="panelGrid">
                        <p:row>
                            <p:column>
                                <h:outputLabel value="#{messages.RangoEdadNombre} *" for="nombre" />
                            </p:column>
                            <p:column>
                                <h:inputText id="nombre" value="#{cnmasRangoEdadController.selected.nombre}" 
                                             required="true" requiredMessage="#{messages.RangoEdadNombreObligatorio}"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column>
                                <h:outputLabel value="#{messages.RangoEdadDesde}" for="desde" />
                            </p:column>
                            <p:column>
                                <h:inputText id="desde" value="#{cnmasRangoEdadController.selected.desde}" />
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column>
                                <h:outputLabel value="#{messages.RangoEdadHasta}" for="hasta" />
                            </p:column>
                            <p:column>
                                <h:inputText id="hasta" value="#{cnmasRangoEdadController.selected.hasta}" />
                            </p:column>
                        </p:row>
                    </p:panelGrid>
                    
                    <div class="actions" style="padding-bottom: 20px; padding-top: 40px;">
                        <h:commandButton id="guardar" value="#{messages.BotonGuardar}" action="#{cnmasRangoEdadController.create}" class="button"/>
                        <h:outputText value="&nbsp;"/>
                        <h:commandButton value="#{messages.BotonCancelar}" action="#{cnmasRangoEdadController.prepareList}" immediate="true" class="button"/>
                    </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>
</html>

web/cnmasRangoEdad/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">#{messages.BreadCrumbEditarRangoEdad}</ui:define>
        <ui:define name="body">
            <h:form>
                <p:breadCrumb>
                    <p:menuitem value="#{messages.BreadCrumbInicio}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbMaestros}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbRangoEdad}" styleClass="itemBreadCrumb" url="./List.xhtml"/>
                    <p:menuitem value="#{messages.BreadCrumbEditarRangoEdad}" styleClass="itemBreadCrumb"/>
                </p:breadCrumb>
            </h:form>
            <br />
            <br />

            <p:dialog header="#{messages.BreadCrumbEditarRangoEdad}" visible="#{not empty facesContext.messageList}" styleClass="dialog">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </p:dialog>

            <h:form id="formId">
                <div class="formulario">
                    <p:panelGrid styleClass="panelGrid">
                        <p:row>
                            <p:column>
                                <h:outputLabel value="#{messages.RangoEdadNombre} *" for="nombre" />
                            </p:column>
                            <p:column>
                                <h:inputText id="nombre" value="#{cnmasRangoEdadController.selected.nombre}" 
                                             required="true" requiredMessage="#{messages.RangoEdadNombreObligatorio}"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column>
                                <h:outputLabel value="#{messages.RangoEdadDesde}" for="desde" />
                            </p:column>
                            <p:column>
                                <h:inputText id="desde" value="#{cnmasRangoEdadController.selected.desde}" />
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column>
                                <h:outputLabel value="#{messages.RangoEdadHasta}" for="hasta" />
                            </p:column>
                            <p:column>
                                <h:inputText id="hasta" value="#{cnmasRangoEdadController.selected.hasta}" />
                            </p:column>
                        </p:row>
                    </p:panelGrid>
                    <div class="actions" style="padding-bottom: 20px; padding-top: 40px;">
                        <h:commandButton value="#{messages.BotonGuardar}" action="#{cnmasRangoEdadController.update}" class="button"/>
                        <h:outputText value="&nbsp;"/>
                        <h:commandButton value="#{messages.BotonCancelar}" action="#{cnmasRangoEdadController.prepareList}" immediate="true" class="button"/>
                    </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>
</html>

web/cnmasRangoEdad/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"> 

    <ui:composition template="/template.xhtml">
        <ui:define name="title">#{messages.BreadCrumbRangoEdad}</ui:define>
        <ui:define name="body">
            <h:form>

                <p:breadCrumb style="width: 250px;">
                    <p:menuitem value="#{messages.BreadCrumbInicio}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbMaestros}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbRangoEdad}" styleClass="itemBreadCrumb"/>
                </p:breadCrumb>
                <br />
                <br />

                <p:dialog header="#{messages.BreadCrumbRangoEdad}" visible="#{not empty facesContext.messageList}" styleClass="dialog">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </p:dialog>

                <div class="tabla">
                    <h:outputText escape="false" value="#{messages.RangoEdadNoExistenDatos}" rendered="#{cnmasRangoEdadController.items.rowCount == 0}"/>

                    <h:panelGroup rendered="#{cnmasRangoEdadController.items.rowCount > 0}">

                        <p:dataTable value="#{cnmasRangoEdadController.items}" var="item" styleClass="dataTable" 
                                     rowIndexVar="rowIndex"
                                     rowStyleClass="#{(rowIndex mod 2) eq 0 ? 'highlight1' : 'highlight2'}" >  
                            <p:column style="width: 5%">
                                <f:facet name="header">
                                    <h:outputText value="#{messages.Id}"/>
                                </f:facet>
                                <h:outputText value="#{item.idRango}" class="itemList"/>
                            </p:column>                             
                            <p:column style="width: 50%">
                                <f:facet name="header">
                                    <h:outputText value="#{messages.RangoEdadNombre}"/>
                                </f:facet>
                                <h:outputText value="#{item.nombre}"  class="itemList"/>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{messages.RangoEdadDesde}"/>
                                </f:facet>
                                <div align="right">
                                    <h:outputText value="#{item.desde}"  class="itemList">
                                        <f:convertNumber type="number" maxFractionDigits="0" locale="es-ES" />
                                    </h:outputText>
                                </div>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{messages.RangoEdadHasta}"/>
                                </f:facet>
                                <div align="right">
                                    <h:outputText value="#{item.hasta}"  class="itemList">
                                       <f:convertNumber type="number" maxFractionDigits="0" locale="es-ES" />
                                    </h:outputText>
                                </div>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{messages.ListaOperaciones}"/>
                                </f:facet>
                                <div align="center">
                                    <h:commandButton action="#{cnmasRangoEdadController.prepareEdit}" image="/images/edit.png" title="#{messages.BotonEditar}"/>
                                    <h:outputText value="&nbsp;"/>
                                    <h:commandButton action="#{cnmasRangoEdadController.destroy}" image="/images/eliminar.png" title="#{messages.BotonEliminar}"
                                                     onclick="return confirm('#{messages.RangoEdadDeseaEliminar}')"/>
                                </div>
                            </p:column>   
                        </p:dataTable>

                    </h:panelGroup>
                    <div>
                        <div class="pagination">
                            <h:commandButton action="#{cnmasRangoEdadController.previous()}" class="buttonPagination" value="#{messages.BotonPrevio}" rendered="#{cnmasRangoEdadController.pagination.hasPreviousPage}"/>&nbsp;                            
                            <ui:repeat var="page" value="#{cnmasRangoEdadController.pagination.pages}">
                                <h:commandButton action="#{cnmasRangoEdadController.toPage(page)}" value="#{page}" class="#{(cnmasRangoEdadController.pagination.isActivePage(page)) ? 'buttonPaginationPage' : 'buttonPagination'}" />&nbsp;
                            </ui:repeat>
                            <h:commandButton action="#{cnmasRangoEdadController.next}" class="buttonPagination" value="#{messages.BotonSiguiente}" rendered="#{cnmasRangoEdadController.pagination.hasNextPage}"/>
                        </div>
                    </div>

                    <br />
                    <div class="actions" style="padding-bottom: 20px;">
                        <h:commandButton value="#{messages.BotonNuevo}"  action="#{cnmasRangoEdadController.prepareCreate}" class="button"/>
                    </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>

</html>