src/java/es/condenast/jsf/CnetlFuenteController.java
package es.condenast.jsf;

import es.condenast.jpa.entities.CnetlFuente;
import es.condenast.jpa.entities.CnetlFuenteValor;
import es.condenast.jpa.entities.CnetlFuenteValorPK;
import es.condenast.jpa.entities.CnetlOrigen;
import es.condenast.jpa.session.CnetlFuenteFacade;
import es.condenast.jpa.session.CnetlFuenteValorFacade;
import es.condenast.jpa.session.CnetlOrigenFacade;
import es.condenast.jsf.util.JsfUtil;
import es.condenast.jsf.util.PaginationHelper;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Named;

@Named("cnetlFuenteController")
@SessionScoped
public class CnetlFuenteController implements Serializable {

    private CnetlFuente current;
    private DataModel items = null;
    @EJB
    private es.condenast.jpa.session.CnetlFuenteFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    @EJB
    private es.condenast.jpa.session.CnetlOrigenFacade ejbOrigenFacade;

    @EJB
    private es.condenast.jpa.session.CnetlFuenteValorFacade ejbFuenteValorFacade;

    // Atributos formulario
    CnetlOrigen valorSeleccionadoBBDD;
    CnetlOrigen[] valoresBBDD;
    CnetlOrigen[] valoresBBDDFuenteTipo;
    List<CnetlFuenteValor> valoresOrigen;
    CnetlFuenteValor valorSeleccionadoOrigen;

    // Estructura interna de origenes
    private HashMap<Integer, CnetlOrigen> origenesHM = new HashMap<>();
    private HashMap<Integer, CnetlOrigen> origenesFuenteTipoHM = new HashMap<>();

    public CnetlFuenteController() {
    }

    public CnetlFuente getSelected() {
        if (current == null) {
            current = new CnetlFuente();
            selectedItemIndex = -1;
        }
        return current;
    }

    private CnetlFuenteFacade getFacade() {
        return ejbFacade;
    }

    public CnetlOrigenFacade getOrigenFacade() {
        return ejbOrigenFacade;
    }

    public CnetlFuenteValorFacade getFuenteValorFacade() {
        return ejbFuenteValorFacade;
    }

    public void setOrigenFacade(CnetlOrigenFacade ejbOrigenFacade) {
        this.ejbOrigenFacade = ejbOrigenFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize() - 1}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (CnetlFuente) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        prepareCreateListas();

        current = new CnetlFuente();
        selectedItemIndex = -1;
        return "Create";
    }

    private void prepareCreateListas() {
        // Inicializar lista
        valoresBBDD = null;
        // Inicializar datatable
        valoresOrigen = new ArrayList<>();
    }

    public String create() {
        try {
            if (!validateFields()) {
                return null;
            }

            getFacade().create(current);
            createFuenteValor();
            return prepareList();
        } catch (Throwable e) {
            String duplicateEntry = JsfUtil.isDuplicateEnty(e);
            if (duplicateEntry != null) {
                if (duplicateEntry.contains("UK_FUENTE_NOMBRE")) {
                    JsfUtil.addErrorMessage(ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("FuenteDatosClaveDuplicada"),
                            new String[]{current.getNombre(), ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("FuenteDatosNombre")});
                }
            } else {
                JsfUtil.addErrorMessage(ResourceBundle.getBundle("resources/Messages").getString("PersistenceErrorOccured"));
            }
            return null;
        }
    }

    private void createFuenteValor() {

        // Valores personalizados
        for (CnetlFuenteValor fvPersonalizados : valoresOrigen) {
            CnetlFuenteValorPK fvPersonalizadosPK = new CnetlFuenteValorPK(current.getIdFuente(), fvPersonalizados.getCnetlOrigen().getIdOrigen());
            fvPersonalizados.setCnetlFuenteValorPK(fvPersonalizadosPK);
            getFuenteValorFacade().create(fvPersonalizados);
        }
    }

    public String prepareEdit() {
        current = (CnetlFuente) getItems().getRowData();
        prepareEditListas();

        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    private void prepareEditListas() {
        // Inicializar datatable
        valoresOrigen = getFuenteValorFacade().findByIdFuente(current.getIdFuente());

        // Lista de Valores de BBDD que no estan en el tipo de fuente
        List<CnetlOrigen> listaOrigenes = getOrigenFacade().findValoresPosibles(false, current.getIdFuenteTipo().getIdFuenteTipo());
        origenesHM = CnetlOrigen.toHashMapId(listaOrigenes);
        for (CnetlFuenteValor valorOrigen : valoresOrigen) {
            listaOrigenes.remove(valorOrigen.getCnetlOrigen());

        }
        Collections.sort(listaOrigenes);

        // Lista de Valores de BBDD que estan en el tipo de fuente
        List<CnetlOrigen> listaOrigenesExistentes = getOrigenFacade().findValoresExistentes(false, current.getIdFuenteTipo().getIdFuenteTipo());
        Collections.sort(listaOrigenesExistentes);
        origenesFuenteTipoHM = CnetlOrigen.toHashMapId(listaOrigenesExistentes);

        listaOrigenesExistentes.toArray(new CnetlOrigen[listaOrigenesExistentes.size()]);
        listaOrigenesExistentes.addAll(listaOrigenes);

        valoresBBDD = listaOrigenesExistentes.toArray(new CnetlOrigen[listaOrigenesExistentes.size()]);

    }

    public String update() {
        try {
            if (!validateFields()) {
                return null;
            }

            getFacade().edit(current);
            performDestroyFuenteValor();
            createFuenteValor();

            return "List";
        } catch (Throwable e) {

            String duplicateEntry = JsfUtil.isDuplicateEnty(e);
            if (duplicateEntry != null) {
                if (duplicateEntry.contains("UK_FUENTE_NOMBRE")) {
                    JsfUtil.addErrorMessage(ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("FuenteDatosClaveDuplicada"),
                            new String[]{current.getNombre(), ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("FuenteDatosNombre")});
                }
            } else {
                JsfUtil.addErrorMessage(ResourceBundle.getBundle("resources/Messages").getString("PersistenceErrorOccured"));
            }
            return null;
        }
    }

    public String destroy() {
        current = (CnetlFuente) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            performDestroyFuenteValor();
            getFacade().remove(current);

        } catch (Exception e) {
            String foreignKey = JsfUtil.isForeignKey(e);

            if (foreignKey != null) {
                if (foreignKey.contains("FK_FUENTE_VALOR_FUENTE")
                        || foreignKey.contains("FK_POOL_FUENTE")) {
                    JsfUtil.addErrorMessage(ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("FuenteDatosForeignKey"),
                            new String[]{current.getNombre()});
                }
            } else {
                JsfUtil.addErrorMessage(ResourceBundle.getBundle("resources/Messages").getString("PersistenceErrorOccured"));
            }
        }
    }

    private void performDestroyFuenteValor() {
        // Valores personalizados
        List<CnetlFuenteValor> valores = getFuenteValorFacade().findByIdFuente(current.getIdFuente());
        for (CnetlFuenteValor fvPersonalizados : valores) {
            CnetlFuenteValorPK fvPersonalizadosPK = new CnetlFuenteValorPK(current.getIdFuente(), fvPersonalizados.getCnetlFuenteValorPK().getIdOrigen());
            fvPersonalizados.setCnetlFuenteValorPK(fvPersonalizadosPK);
            getFuenteValorFacade().remove(fvPersonalizados);
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }

src/java/es/condenast/jsf/VietlLogController.java
package es.condenast.jsf;

import es.condenast.jpa.entities.VietlLog;
import es.condenast.jsf.util.JsfUtil;
import es.condenast.jsf.util.PaginationHelper;
import es.condenast.jpa.session.VietlLogFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("vietlLogController")
@SessionScoped
public class VietlLogController implements Serializable {

    private VietlLog current;
    private DataModel items = null;
    @EJB
    private es.condenast.jpa.session.VietlLogFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public VietlLogController() {
    }

    public VietlLog getSelected() {
        if (current == null) {
            current = new VietlLog();
            selectedItemIndex = -1;
        }
        return current;
    }

    private VietlLogFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (VietlLog) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new VietlLog();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("VietlLogCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (VietlLog) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("VietlLogUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (VietlLog) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("VietlLogDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public VietlLog getVietlLog(long id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = VietlLog.class)
    public static class VietlLogControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            VietlLogController controller = (VietlLogController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "vietlLogController");
            return controller.getVietlLog(getKey(value));
        }

        long getKey(String value) {
            long key;
            key = Long.parseLong(value);
            return key;
        }

        String getStringKey(long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof VietlLog) {
                VietlLog o = (VietlLog) object;
                return getStringKey(o.getIdPool());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + VietlLog.class.getName());
            }
        }

    }

}

web/cnetlFuente/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">


    <h:outputScript library="js" name="condeNast.js" />

    <ui:composition template="/template.xhtml">
        <ui:define name="title">#{messages.BreadCrumbCrearFuenteDatos}</ui:define>
        <ui:define name="body">
            <h:form>
                <p:breadCrumb>
                    <p:menuitem value="#{messages.BreadCrumbInicio}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbOrigenDatos}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbFuenteDatos}" styleClass="itemBreadCrumb" url="./List.xhtml"/>
                    <p:menuitem value="#{messages.BreadCrumbCrearFuenteDatos}" styleClass="itemBreadCrumb"/>
                </p:breadCrumb>
            </h:form>
            <br />
            <br />

            <p:dialog header="#{messages.BreadCrumbCrearFuenteDatos}" visible="#{not empty facesContext.messageList}" styleClass="dialog">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </p:dialog>


            <h:form id="formId">
                <div class="formulario">
                    <p:panelGrid styleClass="panelGrid">
                        <p:row>
                            <p:column>              
                                <h:outputLabel value="#{messages.FuenteDatosNombre} *" for="nombre"  class="etiqueta" />
                            </p:column>
                            <p:column>
                                <h:inputText id="nombre" value="#{cnetlFuenteController.selected.nombre}" />
                            </p:column>
                        </p:row>

                        <p:row>
                            <p:column> 
                                <h:outputLabel value="#{messages.FuenteDatosFuenteTipo} *" for="idFuenteTipo" class="etiqueta" />
                            </p:column>
                            <p:column>
                                <h:selectOneMenu id="idFuenteTipo" value="#{cnetlFuenteController.selected.idFuenteTipo}" 
                                                 style="width: 95%;" onchange="changeFuenteTipo()" >
                                    <f:selectItems value="#{cnetlFuenteTipoController.itemsAvailableSelectOne}"/>
                                </h:selectOneMenu>
                            </p:column>
                        </p:row>



                        <p:row>
                            <p:column> 
                                <h:outputLabel value="#{messages.FuenteDatosOrigen} *" for="origen" class="etiqueta" />
                            </p:column>
                            <p:column>
                                <h:inputText id="origen" value="#{cnetlFuenteController.selected.origen}" />
                            </p:column>
                        </p:row>

                        <p:row>
                            <p:column> 
                                <h:outputLabel value="#{messages.FuenteDatosEsFichero} *" for="esFichero" class="etiqueta" />                           
                            </p:column>
                            <p:column>
                                <p:selectOneRadio id="esFichero" value="#{cnetlFuenteController.selected.esFichero}">
                                    <f:selectItem itemLabel="#{messages.FuenteDatosFichero}" itemValue="true" />
                                    <f:selectItem itemLabel="#{messages.FuenteDatosCarpeta}" itemValue="false" />
                                </p:selectOneRadio>
                            </p:column>
                        </p:row>

                        <p:row>
                            <p:column> 
                                <h:outputLabel value="#{messages.FuenteDatosActivo}" for="activo" class="etiqueta" />                     
                            </p:column>
                            <p:column>
                                <h:selectBooleanCheckbox value="#{cnetlFuenteController.selected.activo}"/>
                            </p:column>
                        </p:row>

                    </p:panelGrid>
                    <br/>
                    <p:panelGrid styleClass="panelGridTable">     
                        <p:row>
                            <p:column style="width: 30%; vertical-align: top;">
                                <div align="center">
                                    #{messages.FuenteDatosValoresPersonalizadosBBDD}
                                </div>     
                                <br/>
                                <h:selectOneListbox id="valorBBDD" value="#{cnetlFuenteController.valorSeleccionadoBBDD}"  size="20" onclick="showDescription();" style="width: 100%;">
                                    <f:selectItems value="#{cnetlFuenteController.valoresBBDD}" var="item" itemDisabled="#{cnetlFuenteController.isDisabled(item)}" />
                                </h:selectOneListbox> 
                                <p:messages severity="info" id="messagesSource" showDetail="true"  closable="true" style="padding-left:  5px !important; width: 315px;" />
                            </p:column>
                            <p:column style="width: 5%;">
                                <div align="center">
                                    <h:commandButton action="#{cnetlFuenteController.insertOrigen}" image="/images/add.png" style="width: 25px;"/>
                                    <br/>
                                    <h:commandButton action="#{cnetlFuenteController.removeOrigen}" image="/images/remove.png" style="width: 25px;"/>
                                </div>
                            </p:column>

                            <p:column style="width: 60%; vertical-align: top;">
                                <div align="center">
                                    #{messages.FuenteDatosValoresPersonalizadosOrigen}
                                </div>     
                                <br/>
                                <p:dataTable id="valores" value="#{cnetlFuenteController.valoresOrigen}" var="origenFuente" 
                                             selectionMode="single" rowKey="#{origenFuente.cnetlOrigen.idOrigen}"
                                             selection="#{cnetlFuenteController.valorSeleccionadoOrigen}"
                                             emptyMessage="">
                                    <p:column> 
                                        <f:facet name="header">  
                                            #{messages.FuenteDatosCampoBBDD}
                                        </f:facet>

                                        <h:outputText value="#{origenFuente.cnetlOrigen.nombre}" />  
                                    </p:column> 
                                    <p:column>  
                                        <f:facet name="header">  
                                            #{messages.FuenteDatosValor}
                                        </f:facet>
                                        <h:inputText  value="#{origenFuente.valor}">
                                            <f:validator validatorId="datoValidator"/>
                                            <f:attribute name="expReg" value="#{origenFuente.cnetlOrigen.idDato.expReg}"/>
                                            <f:attribute name="campoBBDD" value="#{origenFuente.cnetlOrigen.nombre}"/>
                                        </h:inputText>
                                    </p:column>        
                                    <p:column>  
                                        <f:facet name="header">  
                                            #{messages.FuenteDatosFormato}
                                        </f:facet>
                                        <h:outputText  value="#{origenFuente.cnetlOrigen.idDato.descripcion}"/>  
                                    </p:column>                                      
                                </p:dataTable>
                            </p:column>
                        </p:row>
                    </p:panelGrid>



                    <p:remoteCommand name="descriptionOrigen" action="#{cnetlFuenteController.showDescription}" update="messagesSource" immediate="true"/>
                    <p:remoteCommand name="changeFuenteTipoJSF" action="#{cnetlFuenteController.changeFuenteTipo}" update="valorBBDD" immediate="true"/>


                    <div class="actions" style="padding-bottom: 20px; padding-top: 40px;">
                        <h:commandButton id="guardar" value="#{messages.BotonGuardar}" action="#{cnetlFuenteController.create}" class="button"/>
                        <h:outputText value="&nbsp;"/>
                        <h:commandButton value="#{messages.BotonCancelar}" action="#{cnetlFuenteController.prepareList}" immediate="true" class="button"/>
                    </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/cnetlFuente/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">#{messages.BreadCrumbFuenteDatos}</ui:define>
        <ui:define name="body">
            <h:form>

                <p:breadCrumb>
                    <p:menuitem value="#{messages.BreadCrumbInicio}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbOrigenDatos}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbFuenteDatos}" styleClass="itemBreadCrumb"/>
                </p:breadCrumb>
                <br />
                <br />


                <p:dialog header="#{messages.BreadCrumbFuenteDatos}" visible="#{not empty facesContext.messageList}" styleClass="dialog">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </p:dialog>

                <div class="tabla">

                    <h:outputText escape="false" value="#{messages.FuenteDatosNoExistenDatos}" rendered="#{cnetlFuenteController.items.rowCount == 0}"/>

                    <h:panelGroup rendered="#{cnetlFuenteController.items.rowCount > 0}">

                        <p:dataTable value="#{cnetlFuenteController.items}" var="item"  styleClass="dataTable"
                                     rowIndexVar="rowIndex"
                                     rowStyleClass="#{(rowIndex mod 2) eq 0 ? 'highlight1' : 'highlight2'}" >
                            <p:column style="width: 5%">
                                <f:facet name="header">
                                    <h:outputText value="#{messages.Id}"/>
                                </f:facet>
                                <h:outputText value="#{item.idFuente}" class="itemList"/>
                            </p:column>                            
                            <p:column style="width: 75%">
                                <f:facet name="header">
                                    <h:outputText value="#{messages.FuenteDatosNombre}"/>
                                </f:facet>
                                <h:outputText value="#{item.nombre}" class="itemList"/>
                            </p:column>

                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="#{messages.ListaOperaciones}"/>
                                </f:facet>
                                <div align="center">
                                    <h:commandButton action="#{cnetlFuenteController.prepareEdit}" image="/images/edit.png" title="#{messages.BotonEditar}"/>
                                    <h:outputText value="&nbsp;"/>
                                    <h:commandButton action="#{cnetlFuenteController.destroy}" image="/images/eliminar.png" title="#{messages.BotonEliminar}"
                                                     onclick="return confirm('#{messages.FuenteDatosDeseaEliminar}')"/>
                                </div>
                            </p:column>                            

                        </p:dataTable>
                    </h:panelGroup>
                    <div>
                        <div class="pagination">
                            <h:commandButton action="#{cnetlFuenteController.previous()}" class="buttonPagination" value="#{messages.BotonPrevio}" rendered="#{cnetlFuenteController.pagination.hasPreviousPage}"/>&nbsp;                            
                            <ui:repeat var="page" value="#{cnetlFuenteController.pagination.pages}">
                                <h:commandButton action="#{cnetlFuenteController.toPage(page)}" value="#{page}" class="#{(cnetlFuenteController.pagination.isActivePage(page)) ? 'buttonPaginationPage' : 'buttonPagination'}" />&nbsp;
                            </ui:repeat>
                            <h:commandButton action="#{cnetlFuenteController.next}" class="buttonPagination" value="#{messages.BotonSiguiente}" rendered="#{cnetlFuenteController.pagination.hasNextPage}"/>
                        </div>
                    </div>

                    <br />
                    <div class="actions" style="padding-bottom: 20px;">
                        <h:commandButton value="#{messages.BotonNuevo}"  action="#{cnetlFuenteController.prepareCreate}" class="button"/>
                    </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>

</html>