src/java/es/condenast/jsf/CnmasMarcaController.java
package es.condenast.jsf;

import es.condenast.jpa.entities.CnmasMarca;
import es.condenast.jpa.session.CnmasMarcaFacade;
import es.condenast.jsf.util.JsfUtil;
import es.condenast.jsf.util.PaginationHelper;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Named;

@Named("cnmasMarcaController")
@SessionScoped
public class CnmasMarcaController implements Serializable {

    private CnmasMarca current;
    private DataModel items = null;
    @EJB
    private es.condenast.jpa.session.CnmasMarcaFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public CnmasMarcaController() {
    }

    public CnmasMarca getSelected() {
        if (current == null) {
            current = new CnmasMarca();
            selectedItemIndex = -1;
        }
        return current;
    }

    private CnmasMarcaFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (CnmasMarca) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new CnmasMarca();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            return prepareList();
        } catch (Exception e) {
            String duplicateEntry = JsfUtil.isDuplicateEnty(e);
            if (duplicateEntry != null) {
                if (duplicateEntry.contains("UK_MARCA_NOMBRE")) {
                    JsfUtil.addErrorMessage(ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("MarcaClaveDuplicada"),
                            new String[]{current.getNombre(), ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("MarcaNombre")});
                }
            } else {
                JsfUtil.addErrorMessage(ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("PersistenceErrorOccured"));
            }
            return null;
        }
    }

    public String prepareEdit() {
        current = (CnmasMarca) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            return prepareList();
        } catch (Exception e) {
            String duplicateEntry = JsfUtil.isDuplicateEnty(e);
            if (duplicateEntry != null) {
                if (duplicateEntry.contains("UK_MARCA_NOMBRE")) {
                    JsfUtil.addErrorMessage(ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("MarcaClaveDuplicada"),
                            new String[]{current.getNombre(), ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("MarcaNombre")});
                }
            } else {
                JsfUtil.addErrorMessage(ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("PersistenceErrorOccured"));
            }
            return null;
        }
    }

    public String destroy() {
        current = (CnmasMarca) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        List<CnmasMarca> marcas =  ejbFacade.findAll();
        ArrayList<CnmasMarca> newMarcas = new ArrayList<>();
        for (CnmasMarca marca: marcas) {
            if (!marca.getNombre().equals("Otros")) newMarcas.add(marca);
        }
        return JsfUtil.getSelectItems(newMarcas, false);
        //return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }
    
        public SelectItem[] getItemsAvailableSelectOneSinGuion() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }
    
    public CnmasMarca getCnmasMarca(java.lang.Short id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = CnmasMarca.class)
    public static class CnmasMarcaControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CnmasMarcaController controller = (CnmasMarcaController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "cnmasMarcaController");
            return controller.getCnmasMarca(getKey(value));
        }

        java.lang.Short getKey(String value) {
            java.lang.Short key;
            key = Short.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Short value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof CnmasMarca) {
                CnmasMarca o = (CnmasMarca) object;
                return getStringKey(o.getIdMarca().shortValue());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + CnmasMarca.class.getName());
            }
        }

    }

}

web/cncrmUsuario/Delete.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

    <h:outputScript library="js" name="condeNast.js" />

    <ui:composition template="/template.xhtml">
        <ui:define name="title">#{messages.BreadCrumbUsuariosCRM}</ui:define>
        <ui:define name="body">
            <h:form>
                <p:breadCrumb>
                    <p:menuitem value="#{messages.BreadCrumbInicio}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbMaestros}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbUsuariosCRM}" styleClass="itemBreadCrumb"/>
                </p:breadCrumb>
            </h:form>
            <br />

            <p:dialog header="#{messages.BreadCrumbUsuariosCRM}" visible="#{not empty facesContext.messageList}" styleClass="dialog">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </p:dialog>

            <div class="formulario" style="text-align: center;">
                <p:panelGrid styleClass="panelGrid">
                    <p:row>
                        <p:column> 
                            <h:outputLabel value="#{messages.UsuariosCRMAdvertencia}" style="color: red; font-size: 1.5em;" />
                        </p:column>
                    </p:row>
                </p:panelGrid>
            </div>
            <br />
            <br />


            <h:form id="formDesactivarId" onkeypress="if (event.keyCode == 13) {  return false; }">
                <div class="formulario">
                    <p:panelGrid styleClass="panelGrid">

                        <p:row>
                            <p:column> 
                                <h:outputLabel value="#{messages.UsuariosCRMEmail} *" for="email" />
                            </p:column>
                            <p:column>
                                <h:inputText id="email" value="#{cncrmUsuarioController.selected.email}" 
                                             required="true" requiredMessage="#{messages.UsuariosCRMEmailObligatorio}"
                                             title="#{messages.UsuariosCRMEmailsToolTip}">
                                    <f:validator validatorId="emailValidator" />
                                </h:inputText>
                            </p:column>
                        </p:row>

                        <p:row>
                            <p:column> 
                                <h:outputLabel value="#{messages.UsuariosCRMMarcas} *" />
                            </p:column>
                            <p:column>
                                <h:selectManyListbox value="#{cncrmUsuarioController.marcas}" size="7" style="width: 95%;"
                                                     required="true" requiredMessage="#{messages.UsuariosCRMMarcasObligatorio}">
                                    <f:selectItems  value="#{cnmasMarcaController.itemsAvailableSelectOneSinGuion}"/>
                                </h:selectManyListbox>
                            </p:column>
                        </p:row>
                    </p:panelGrid>

                    <p:confirmDialog header="Desactivar Usuario" message="¿Está seguro que desea desactivar a este usuario?" widgetVar="confDesactivar">
                        <h:commandButton value="Si" class="button" styleClass="ui-confirmdialog-yes" immediate="true" action="#{cncrmUsuarioController.desactivar}"/>
                        <h:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" onclick="PF('confDesactivar').hide()" />
                    </p:confirmDialog>

                    <p:confirmDialog header="Desactivar Usuario" message="No existe un registro para el email/marca(s) seleccionadas o el usuario ya está desactivado para la marca(s) seleccionada(s)" widgetVar="confDesactivar0">
                        <h:commandButton value="Aceptar" type="button" styleClass="ui-confirmdialog-no" onclick="PF('confDesactivar0').hide()" />
                    </p:confirmDialog>

                    <div class="actions" style="padding-bottom: 20px; padding-top: 20px;">
                        <h:commandButton id="desactivar" value="#{messages.BotonDesactivar}" action="#{cncrmUsuarioController.preguntaDesactivar}" class="button"/>
                    </div>
                </div>                    
            </h:form>

            <h:form id="formBorrarEmailId" onkeypress="if (event.keyCode == 13) {  return false; }">
                <div class="formulario">
                    <p:panelGrid styleClass="panelGrid">

                        <p:row>
                            <p:column> 
                                <h:outputLabel value="#{messages.UsuariosCRMEmails} *"  />
                            </p:column>
                            <p:column>
                                <h:inputText id="email" value="#{cncrmUsuarioController.emails}" 
                                             required="true" requiredMessage="#{messages.UsuariosCRMEmailsObligatorio}" title="#{messages.UsuariosCRMEmailsBajaToolTip}" >
                                    <f:validator validatorId="emailValidator" />
                                </h:inputText>
                            </p:column>
                        </p:row>
                    </p:panelGrid>

                    <c:if test="#{cncrmUsuarioController.numeroRegistros > 0}">
                        <p:confirmDialog header="Eliminar" message="¿Está seguro que desea eliminar a este usuario(s)?" widgetVar="confirmacionPorEmail">
                            <h:commandButton value="Si" class="button" styleClass="ui-confirmdialog-yes" immediate="true" action="#{cncrmUsuarioController.eliminarPorEmails}"/>
                            <h:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" onclick="PF('confirmacionPorEmail').hide()" />
                        </p:confirmDialog>
                    </c:if>

                    <c:if test="#{cncrmUsuarioController.numeroRegistros == 0}">
                        <p:confirmDialog header="Eliminar" message="No existen usuarios en la BBDD con estos emails" widgetVar="confirmacionPorEmail0">
                            <h:commandButton value="Aceptar" type="button" styleClass="ui-confirmdialog-no" onclick="PF('confirmacionPorEmail0').hide()" />
                        </p:confirmDialog>
                    </c:if>                    


                    <div class="actions" style="padding-bottom: 20px; padding-top: 20px;">
                        <h:commandButton id="guardar" value="#{messages.BotonEliminar}" action="#{cncrmUsuarioController.countPorEmails}" class="button"/>
                    </div>
                </div>                    
            </h:form>

            <h:form id="formBorrarFechaId" onkeypress="if (event.keyCode == 13) {  return false; }">
                <div class="formulario">
                    <p:panelGrid styleClass="panelGrid">

                        <p:row>
                            <p:column> 
                                <h:outputLabel value="#{messages.UsuariosCRMFecha} * (Fecha de baja de los productos)" />
                            </p:column>
                            <p:column>
                                <p:calendar styleClass="dateTimeField" id="fecha" value="#{cncrmUsuarioController.fecha}"  
                                            showOn="button" locale="es" navigator="true" pattern="dd/MM/yyyy" mask="true" 
                                            required="true" requiredMessage="#{messages.UsuariosCRMFechaObligatorio}"
                                            title="#{messages.UsuariosCRMFechaBajaToolTip}"/>
                            </p:column>
                        </p:row>
                    </p:panelGrid>

                    <c:if test="#{cncrmUsuarioController.numeroRegistros > 0}">
                        <p:confirmDialog header="Eliminar" message="¿Desea eliminar #{cncrmUsuarioController.numeroRegistros} usuarios?" widgetVar="confirmacionPorFecha">
                            <h:commandButton value="Si" class="button" styleClass="ui-confirmdialog-yes" immediate="true" action="#{cncrmUsuarioController.eliminarPorFecha}"/>
                            <h:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" onclick="PF('confirmacionPorFecha').hide()" />
                        </p:confirmDialog>
                    </c:if>

                    <c:if test="#{cncrmUsuarioController.numeroRegistros eq 0}">
                        <p:confirmDialog header="Eliminar" message="No existen usuarios en la BBDD anteriores a la fecha introducida" widgetVar="confirmacionPorFecha0">
                            <h:commandButton value="Aceptar" type="button" styleClass="ui-confirmdialog-no" onclick="PF('confirmacionPorFecha0').hide()" />
                        </p:confirmDialog>
                    </c:if>


                    <div class="actions" style="padding-bottom: 20px; padding-top: 20px;">
                        <h:commandButton id="eliminar" value="#{messages.BotonEliminar}" action="#{cncrmUsuarioController.countPorFecha}" class="button"/>
                    </div>
                </div>                    
            </h:form>
        </ui:define>
    </ui:composition>

    <h:outputScript library="js" name="calendar_es.js" />

</html>