src/java/es/condenast/jsf/CargaManualController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.condenast.jsf;

import es.condenast.ingesta.Proceso;
import es.condenast.ingesta.helper.FileUtils;
import es.condenast.jpa.entities.CnetlFuente;
import es.condenast.jpa.entities.CnetlMaster;
import es.condenast.jpa.session.CnetlFuenteFacade;
import es.condenast.jpa.session.CnetlMasterFacade;
import es.condenast.jpa.session.CnetlPoolFacade;
import es.condenast.jpa.session.CnetlPoolLogWarningFacade;
import es.condenast.jpa.session.CnetlPoolMasterFacade;
import es.condenast.jpa.session.CnetlPoolMasterLogWarningFacade;
import es.condenast.jpa.session.VietlLogFacade;
import es.condenast.jpa.session.VietlLogReglaFacade;
import es.condenast.jpa.session.VietlLogTransformacionFacade;
import es.condenast.jpa.session.VietlLogValidacionFacade;
import es.condenast.jpa.session.VietlLogValidacionLineaFacade;
import es.condenast.jsf.util.JsfUtil;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Serializable;
import java.io.Writer;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import javax.servlet.http.Part;
import net.neoremind.sshxcute.core.ConnBean;
import net.neoremind.sshxcute.core.Result;
import net.neoremind.sshxcute.core.SSHExec;
import net.neoremind.sshxcute.exception.TaskExecFailException;
import net.neoremind.sshxcute.task.CustomTask;
import net.neoremind.sshxcute.task.impl.ExecCommand;
import net.neoremind.sshxcute.task.impl.ExecShellScript;
import org.primefaces.context.RequestContext;

@Named("cargaManualController")
@SessionScoped
public class CargaManualController implements Serializable {
    private static final String SSH_HOST = "process.ssh.host";
    private static final String SSH_USER = "process.ssh.user";
    private static final String SSH_PASSWORD = "process.ssh.password";
    private static final String SSH_SHELL_PATH = "process.ssh.shellPath";
    private static final String SSH_SHELL_SCRIPT = "process.ssh.shellScript";
    private Part file;
    private CnetlFuente fuente;
    private CnetlMaster master;

    @EJB
    private es.condenast.jpa.session.CnetlPoolFacade ejbPoolFacade;
    
    @EJB
    private es.condenast.jpa.session.CnetlFuenteFacade ejbFuenteFacade;
    
    @EJB
    private es.condenast.jpa.session.CnetlPoolMasterFacade ejbPoolMasterFacade;

    @EJB
    private es.condenast.jpa.session.CnetlMasterFacade ejbMasterFacade;

    @EJB
    private es.condenast.jpa.session.CnetlPoolLogWarningFacade ejbLogWarningFacade = new CnetlPoolLogWarningFacade();

    @EJB
    private es.condenast.jpa.session.CnetlPoolMasterLogWarningFacade ejbMasterLogWarningFacade = new CnetlPoolMasterLogWarningFacade();
    
    @EJB
    private es.condenast.jpa.session.VietlLogFacade ejbLogFacade = new VietlLogFacade();

    @EJB
    private es.condenast.jpa.session.VietlLogReglaFacade ejbLogReglaFacade = new VietlLogReglaFacade();

    @EJB
    private es.condenast.jpa.session.VietlLogTransformacionFacade ejbLogTransformacionFacade = new VietlLogTransformacionFacade();

    @EJB
    private es.condenast.jpa.session.VietlLogValidacionFacade ejbLogValidacionFacade = new VietlLogValidacionFacade();

    @EJB
    private es.condenast.jpa.session.VietlLogValidacionLineaFacade ejbLogValidacionLineaFacade = new VietlLogValidacionLineaFacade();

    public CargaManualController() {
    }

    public CnetlPoolFacade getPoolFacade() {
        return ejbPoolFacade;
    }

    public void setPoolFacade(CnetlPoolFacade ejbPoolFacade) {
        this.ejbPoolFacade = ejbPoolFacade;
    }

    public CnetlFuenteFacade getFuenteFacade() {
        return ejbFuenteFacade;
    }

    public void setFuenteFacade(CnetlFuenteFacade ejbFuenteFacade) {
        this.ejbFuenteFacade = ejbFuenteFacade;
    }

    public CnetlPoolMasterFacade getPoolMasterFacade() {
        return ejbPoolMasterFacade;
    }

    public void setPoolMasterFacade(CnetlPoolMasterFacade ejbPoolMasterFacade) {
        this.ejbPoolMasterFacade = ejbPoolMasterFacade;
    }

    public CnetlMasterFacade getMasterFacade() {
        return ejbMasterFacade;
    }

    public void setMasterFacade(CnetlMasterFacade ejbMasterFacade) {
        this.ejbMasterFacade = ejbMasterFacade;
    }
    
    public VietlLogFacade getLogFacade() {
        return ejbLogFacade;
    }

    public void setLogFacade(VietlLogFacade ejbLogFacade) {
        this.ejbLogFacade = ejbLogFacade;
    }

    public VietlLogReglaFacade getLogReglaFacade() {
        return ejbLogReglaFacade;
    }

    public void setLogReglaFacade(VietlLogReglaFacade ejbLogReglaFacade) {
        this.ejbLogReglaFacade = ejbLogReglaFacade;
    }

    public VietlLogTransformacionFacade getLogTransformacionFacade() {
        return ejbLogTransformacionFacade;
    }

    public void setLogTransformacionFacade(VietlLogTransformacionFacade ejbLogTransformacionFacade) {
        this.ejbLogTransformacionFacade = ejbLogTransformacionFacade;
    }

    public VietlLogValidacionFacade getLogValidacionFacade() {
        return ejbLogValidacionFacade;
    }

    public void setLogValidacionFacade(VietlLogValidacionFacade ejbLogValidacionFacade) {
        this.ejbLogValidacionFacade = ejbLogValidacionFacade;
    }

    public VietlLogValidacionLineaFacade getLogValidacionLineaFacade() {
        return ejbLogValidacionLineaFacade;
    }

    public void setLogValidacionLineaFacade(VietlLogValidacionLineaFacade ejbLogValidacionLineaFacade) {
        this.ejbLogValidacionLineaFacade = ejbLogValidacionLineaFacade;
    }

    public CnetlPoolLogWarningFacade getLogWarningFacade() {
        return ejbLogWarningFacade;
    }

    public void setLogWarningFacade(CnetlPoolLogWarningFacade ejbLogWarningFacade) {
        this.ejbLogWarningFacade = ejbLogWarningFacade;
    }
    
    public CnetlPoolMasterLogWarningFacade getMasterLogWarningFacade() {
        return ejbMasterLogWarningFacade;
    }

    public void setMasterLogWarningFacade(CnetlPoolMasterLogWarningFacade ejbMasterLogWarningFacade) {
        this.ejbMasterLogWarningFacade = ejbMasterLogWarningFacade;
    }

    public String prepareCargaManual() {
        return "CargaManual";
    }

    public String procesar() throws IOException {

        if(file == null){
            String msg = ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("CargaManualRutaObligatoria");          
            JsfUtil.addErrorMessage(msg);
            return "";
        }
        if(fuente == null){
            String msg = ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("CargaManualFuentesObligatoria");          
            JsfUtil.addErrorMessage(msg);
            return "";
        }
        InputStreamReader isr = new InputStreamReader(file.getInputStream(), "UTF-8");
        String nombreFichero = FileUtils.TMP_DIR + FileUtils.FILE_SEPARATOR + getFilename(file);
        nombreFichero = nombreFichero.replaceAll("/", "////");

        Writer out = new BufferedWriter(new OutputStreamWriter(
                new FileOutputStream(nombreFichero), "UTF-8"));
        try {
            out.write(readFully(file.getInputStream(),"UTF-8"));
        } finally {
            out.close();
        }

        return procesarFichero(nombreFichero);

    }

    public String procesarMaster() throws IOException {

        if(file == null){
            String msg = ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("CargaManualRutaObligatoria");          
            JsfUtil.addErrorMessage(msg);
            return "";
        }
        if(master == null){
            String msg = ResourceBundle.getBundle(JsfUtil.MESSAGES).getString("CargaManualFuentesObligatoria");          
            JsfUtil.addErrorMessage(msg);
            return "";
        }
        InputStreamReader isr = new InputStreamReader(file.getInputStream(), "UTF-8");
        String nombreFichero = FileUtils.TMP_DIR + FileUtils.FILE_SEPARATOR + getFilename(file);
        nombreFichero = nombreFichero.replace("\\", "\\\\");
        
        Writer out = new BufferedWriter(new OutputStreamWriter(
                new FileOutputStream(nombreFichero), "UTF-8"));
        try {
            out.write(readFully(file.getInputStream(),"UTF-8"));
        } finally {
            out.close();
        }

        return procesarFicheroMaster(nombreFichero);

    }
    
    public String readFully(InputStream inputStream, String encoding)
            throws IOException {
        return new String(readFully(inputStream), encoding);
    }

    private byte[] readFully(InputStream inputStream)
            throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        byte[] buffer = new byte[1024];
        int length = 0;
        while ((length = inputStream.read(buffer)) != -1) {
            baos.write(buffer, 0, length);
        }
        return baos.toByteArray();
    }

    private static String getFilename(Part part) {
        for (String cd : part.getHeader("content-disposition").split(";")) {
            if (cd.trim().startsWith("filename")) {
                String filename = cd.substring(cd.indexOf('=') + 1).trim().replace("\"", "");
                return filename.substring(filename.lastIndexOf('/') + 1).substring(filename.lastIndexOf('\\') + 1); // MSIE fix.  
            }
        }
        return null;
    }

    public Part getFile() {
        return file;
    }

    public void setFile(Part file) {
        this.file = file;
    }

    public String procesarFichero(String ruta) {

        Proceso.setPoolFacade(getPoolFacade());
        Proceso.setLogFacade(getLogFacade());

src/java/es/condenast/jsf/VietlLogController.java
package es.condenast.jsf;

import es.condenast.jpa.entities.VietlLog;
import es.condenast.jsf.util.JsfUtil;
import es.condenast.jsf.util.PaginationHelper;
import es.condenast.jpa.session.VietlLogFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("vietlLogController")
@SessionScoped
public class VietlLogController implements Serializable {

    private VietlLog current;
    private DataModel items = null;
    @EJB
    private es.condenast.jpa.session.VietlLogFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public VietlLogController() {
    }

    public VietlLog getSelected() {
        if (current == null) {
            current = new VietlLog();
            selectedItemIndex = -1;
        }
        return current;
    }

    private VietlLogFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (VietlLog) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new VietlLog();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("VietlLogCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (VietlLog) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("VietlLogUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (VietlLog) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("VietlLogDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle(JsfUtil.BUNDLE).getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public VietlLog getVietlLog(long id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = VietlLog.class)
    public static class VietlLogControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            VietlLogController controller = (VietlLogController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "vietlLogController");
            return controller.getVietlLog(getKey(value));
        }

        long getKey(String value) {
            long key;
            key = Long.parseLong(value);
            return key;
        }

        String getStringKey(long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof VietlLog) {
                VietlLog o = (VietlLog) object;
                return getStringKey(o.getIdPool());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + VietlLog.class.getName());
            }
        }

    }

}

web/cargaManual/CargaManual.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">


    <ui:composition template="/template.xhtml">
        <ui:define name="title">#{messages.BreadCrumbCargaManual}</ui:define>
        <ui:define name="body">
            <h:form>
                <p:breadCrumb styleClass="breadCrumb">
                    <p:menuitem value="#{messages.BreadCrumbInicio}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbCargaManual}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbCargaManualIngesta}" styleClass="itemBreadCrumb"/>
                </p:breadCrumb>
            </h:form>
            <br />
            <br />

            <p:dialog header="#{messages.BreadCrumbCargaManual}" visible="#{not empty facesContext.messageList}" styleClass="dialog">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </p:dialog>

            <h:form id="formId" enctype="multipart/form-data">

                <div class="formulario">
                    <p:panelGrid styleClass="panelGrid">
                        <p:row>
                            <p:column>
                                <h:outputLabel value="#{messages.CargaManualRuta} *" class="etiqueta" />
                            </p:column>
                            <p:column>
                                 <h:inputFile value="#{cargaManualController.file}"  label="Examinar" />
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column>
                                <h:outputLabel value="#{messages.CargaManualFuentes} *" />
                            </p:column>
                            <p:column>
                                <p:selectOneRadio value="#{cargaManualController.fuente}" layout="pageDirection" 
                                                  style="width: 100% !important;">
                                    <f:selectItems value="#{cnetlFuenteController.itemsAvailableSelectMany}"/>
                                </p:selectOneRadio>
                                
                            </p:column>
                        </p:row>
                    </p:panelGrid>
                    <div class="actions" style="padding-bottom: 20px; padding-top: 40px;">
                        <h:commandButton value="#{messages.BotonProcesar}" action="#{cargaManualController.procesar()}" onclick="PF('waitPanel').show()" class="button"/>
                        <h:outputText value="&nbsp;"/>
                        <h:commandButton id="desactivar" value="#{messages.BotonProcesarTodo}" action="#{cargaManualController.informarProcesarTodo}" onclick="PF('waitPanel').show()" class="button"/>
                        <p:confirmDialog header="#{messages.BotonProcesarTodo}" message="#{messages.CargaManualinformarProcesarTodo}" widgetVar="dialogProcesarTodo">
                            <h:commandButton value="Si" class="button" styleClass="ui-confirmdialog-yes">
                                <p:ajax event="click" class="ui-confirmdialog-si" listener="#{cargaManualController.procesarTodo()}" onstart="PF('dialogProcesarTodo').hide(); PF('waitPanel').show()" onerror="alert('Errorrrr')"/> 
                            </h:commandButton>
                            <h:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" onclick="PF('dialogProcesarTodo').hide()" />
                        </p:confirmDialog>
                    </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>
</html>

web/cargaManual/CargaMaster.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">


    <ui:composition template="/template.xhtml">
        <ui:define name="title">#{messages.BreadCrumbCargaManual}</ui:define>
        <ui:define name="body">
            <h:form>
                <p:breadCrumb styleClass="breadCrumb">
                    <p:menuitem value="#{messages.BreadCrumbInicio}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbCargaManual}" styleClass="itemBreadCrumb"/>
                    <p:menuitem value="#{messages.BreadCrumbCargaManualMaster}" styleClass="itemBreadCrumb"/>
                </p:breadCrumb>
            </h:form>
            <br />
            <br />

            <p:dialog header="#{messages.BreadCrumbCargaManual}" visible="#{not empty facesContext.messageList}" styleClass="dialog">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </p:dialog>

            <h:form id="formId" enctype="multipart/form-data">

                <div class="formulario">
                    <p:panelGrid styleClass="panelGrid">
                        <p:row>
                            <p:column>
                                <h:outputLabel value="#{messages.CargaManualRuta} *" class="etiqueta" />
                            </p:column>
                            <p:column>
                                 <h:inputFile value="#{cargaManualController.file}"  label="Examinar" />
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column>
                                <h:outputLabel value="#{messages.CargaManualFuentes} *" />
                            </p:column>
                            <p:column>
                                <p:selectOneRadio value="#{cargaManualController.master}" layout="pageDirection" 
                                                  style="width: 100% !important;">
                                    <f:selectItems value="#{cnetlMasterController.itemsAvailableSelectMany}"/>
                                </p:selectOneRadio>
                                
                            </p:column>
                        </p:row>
                    </p:panelGrid>
                    <div class="actions" style="padding-bottom: 20px; padding-top: 40px;">
                        <h:commandButton value="#{messages.BotonProcesar}" action="#{cargaManualController.procesarMaster()}" onclick="PF('waitPanel').show()" class="button"/>
                    </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>
</html>